title: Chiloh Wei
description: "一个尝试理解世界，理解自己的人"

github: chilohwei
twitter: chiloh_cn
v2ex: Y2hpbG9o

url: /
menu:
  - title: 'Categories'
    url: '/categories.html'
  - title: 'About'
    url: '/about'
  - title: 'RSS'
    url: '/feed.xml'

timezone:    Africa/El_Aaiun
locale:      zh_CN
lang:      zh-cmn-Hans
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:title.html
assetUrl: /images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==

google_analytics: 
baidu_verify: 
google_verify: 

paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

showBuyCoffee: false
payImage: 

include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "package.json","node_modules"]
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
