# Site Information
title: Chiloh Wei
description: "一个尝试理解世界，理解自己的人"
url: https://blog.chiloh.com
repo: chilohwei/chilohwei.github.io
lang: zh-CN
timezone: Africa/El_Aaiun

# Social Media and External URLs
github: chilohwei
zhihu: 
twitter: chiloh_wei
v2ex: 
menu:
  - title: "Categories"
    url: "/categories.html"
  - title: "About"
    url: "/about.html"

# SEO and Analytics
google_analytics: G-3G9RLF9G44

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html
  posts_en:
    output: true
    permalink: /en/:year-:month-:day/:title.html
    sort_by: date

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-feed

# Custom Site Settings
showBuyCoffee: true
payImage: //chilohdata.s3.bitiful.net/zanshang.JPG?dpr=0.5
assetUrl: //blog.chiloh.com/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
