# Development configuration overrides
url: "http://localhost:4000"
baseurl: ""

# Enable development features
show_drafts: true
livereload: true
incremental: true

# Disable analytics in development
google_analytics: ""
